CREATE DATABASE SUDHAR;

USE SUDHAR;

-- STUDENT TABLE --

CREATE TABLE STUDENT(
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
	FIRST_NAME VARCHAR(255) NOT NULL,
	LAST_NAME VARCHAR(255) NOT NULL,
	USERNAME VARCHAR(255) UNIQUE NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(320) UNIQUE NOT NULL,
	PHONE_NUMBER INTEGER UNIQUE NOT NULL,
	ENGINEERING_BRANCH VARCHAR(255) NOT NULL,
	GENDER VARCHAR(10),
	STATE VARCHAR(255) NOT NULL,
	CITY VARCHAR(255) NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT NOW()
	);

-- COLLEGE TABLE --

CREATE TABLE COLLEGE(
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
	COLLEGE_NAME VARCHAR(255) UNIQUE NOT NULL
	);

-- COURSE TABLE --

CREATE TABLE COURSE(
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
	COURSE_ID VARCHAR(255) UNIQUE NOT NULL,
	COURSE_NAME VARCHAR(255) UNIQUE NOT NULL,
	COURSE_BRANCH VARCHAR(255),
	COURSE_DESCRIPTION TEXT
	);

-- COLLEGE STUDENT --

CREATE TABLE COLLEGE_STUDENT(
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
	STUDENT_ID INTEGER,
	COURSE_ID INTEGER,
	COLLEGE_ID INTEGER,
	FOREIGN KEY STUDENT_ID REFERENCES STUDENT(id),
	FOREIGN KEY COURSE_ID REFERENCES COURSE(id),
	FOREIGN KEY COLLEGE_ID REFERENCES COLLEGE(id)
	);

